### ISSUE TITLE
Data socket does not work

### ISSUE THREAD

**Issue by hitessh18** [arthachitra/FyersAPI#2]
I have been using the api for about 6 months now. recently i got http:/503 error on the order socket. I updated the code with your update. i was gettting the quotes till yesterday. but today, the data socket was connected, but i did not receive any quotes.

i also tested with your test app. it also didnt work.

**Comment by arthachitra** [comment]
Hi,
The order socket has been updated by Fyers and as such we have released a new version. Please download the same from
https://www.nuget.org/packages/ArthaChitra.FyersAPI/2.0.5

The Github code too is duly updated.

**Comment by hitessh18** [comment]
Thank you for such a quick response. I updated with the new version. it is working now :)
    On Wednesday, 23 February 2022, 10:00:47 am IST, ArthaChitra ***@***.***> wrote:  
 
 


Hi,
The order socket has been updated by Fyers and as such we have released a new version. Please download the same from
https://www.nuget.org/packages/ArthaChitra.FyersAPI/2.0.5

The Github code too is duly updated.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hitessh18** [comment]
Hello,
Thanks for the update. I could use it after the update.

There's one small glitch that I am experiencing though. 
I do not get the quote data every time I subscribe to a stock. 
here's what I do.
1. Authorise and open the data socket using your API.(valid login and IsAuthenticated)
2. fetch a list of stocks and subscribe to each stock in a loop.

The data socket is open. But I sometimes do not get the quotes. I have to restart the app a couple of times before I get the quotes. Is it something to with an open data socket? do I need to close the socket when I close my app? how to do it?

Please help.
Regards, 
Hitesh Sharma

**Comment by arthachitra** [comment]
Hi,
You can use the `LogoutAsync()` method to close the sockets.

Please write to Fyers about the scenario as it seems more of a server side scenario.
